# Generated by Django 4.0.3 on 2022-04-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_events_event_date_remove_events_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_address',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_location',
        ),
        migrations.AlterField(
            model_name='events',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
