# Generated by Django 4.0.3 on 2022-04-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_events_event_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='events',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
