# Generated by Django 4.0.3 on 2022-04-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_events_event_id_events_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_address',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='events',
            name='event_date',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='events',
            name='event_location',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='events',
            name='event_time',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
